import { Link } from 'react-router-dom'
import { Eye, FileText, Shield, AlertTriangle, CheckCircle } from 'lucide-react'

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-dark-950 text-white">
      {/* Header */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-dark-950/90 backdrop-blur-xl border-b border-white/5">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <Link to="/" className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary-500 to-accent-500 flex items-center justify-center">
                <Eye className="w-5 h-5 text-white" />
              </div>
              <span className="text-xl font-semibold">ET Analytics</span>
            </Link>
            <Link to="/" className="text-gray-400 hover:text-white transition-colors">
              ← Back to Home
            </Link>
          </div>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 pt-32 pb-20">
        <div className="mb-8">
          <h1 className="text-5xl font-bold mb-4">Terms of Service</h1>
          <p className="text-gray-400">Last updated: January 2026</p>
        </div>

        <div className="card-glass rounded-xl p-6 mb-8 bg-primary-500/10 border-primary-500/20">
          <p className="text-sm text-gray-300">
            <strong>Important:</strong> These Terms of Service should be reviewed by qualified legal counsel before publication. 
            This document is provided as a template and may not reflect all legal requirements applicable to your specific situation.
          </p>
        </div>

        <div className="prose prose-invert prose-lg max-w-none space-y-8">
          {/* Introduction */}
          <section>
            <h2 className="text-3xl font-bold mb-4">1. Agreement to Terms</h2>
            <p className="text-gray-300 mb-4">
              These Terms of Service ("Terms") constitute a legally binding agreement between you (the "Client", "you", or "your") 
              and ETAnalytics Ltd. ("ETAnalytics", "we", "us", or "our") governing your access to and use of the ETAnalytics 
              platform, including our website, software, APIs, and related services (collectively, the "Services").
            </p>
            <p className="text-gray-300 mb-4">
              <strong>By accessing or using our Services, you agree to be bound by these Terms.</strong> If you do not agree to 
              these Terms, you must not access or use the Services.
            </p>
            <p className="text-gray-300">
              These Terms apply to all users of the Services, including ETF issuers, authorised personnel, and any other parties 
              accessing the platform on behalf of a Client organisation.
            </p>
          </section>

          {/* Definitions */}
          <section>
            <h2 className="text-3xl font-bold mb-4">2. Definitions</h2>
            <div className="card-glass rounded-xl p-6">
              <dl className="space-y-4 text-sm">
                <div>
                  <dt className="font-semibold text-white">"Services"</dt>
                  <dd className="text-gray-400 ml-4">The ETAnalytics beneficial ownership analytics platform, including entity matching, 
                  disclosure management, reporting, and related features.</dd>
                </div>
                <div>
                  <dt className="font-semibold text-white">"Share Register Data"</dt>
                  <dd className="text-gray-400 ml-4">Shareholder register files, holdings data, and related information provided by you 
                  for analysis.</dd>
                </div>
                <div>
                  <dt className="font-semibold text-white">"Analysis Results"</dt>
                  <dd className="text-gray-400 ml-4">Reports, insights, entity identifications, and other outputs generated by our 
                  Services from your Share Register Data.</dd>
                </div>
                <div>
                  <dt className="font-semibold text-white">"Authorised User"</dt>
                  <dd className="text-gray-400 ml-4">An individual designated by you to access and use the Services on behalf of your 
                  organisation.</dd>
                </div>
                <div>
                  <dt className="font-semibold text-white">"Subscription Term"</dt>
                  <dd className="text-gray-400 ml-4">The period during which you have an active paid subscription to the Services.</dd>
                </div>
              </dl>
            </div>
          </section>

          {/* Services Description */}
          <section>
            <h2 className="text-3xl font-bold mb-4">3. Description of Services</h2>
            <p className="text-gray-300 mb-4">ETAnalytics provides the following Services:</p>
            
            <div className="space-y-4">
              <div className="card-glass rounded-xl p-6">
                <h4 className="font-semibold mb-2 flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-primary-400" />
                  Entity Matching and Identification
                </h4>
                <p className="text-gray-400 text-sm">
                  Automated identification of custodians, platforms, wealth managers, and investment decision makers from 
                  nominee account names using proprietary databases and matching algorithms.
                </p>
              </div>

              <div className="card-glass rounded-xl p-6">
                <h4 className="font-semibold mb-2 flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-accent-400" />
                  Disclosure Request Management
                </h4>
                <p className="text-gray-400 text-sm">
                  Generation of compliant beneficial ownership disclosure requests under relevant legal frameworks 
                  (including but not limited to Irish Companies Act provisions), submission management, and response tracking.
                </p>
              </div>

              <div className="card-glass rounded-xl p-6">
                <h4 className="font-semibold mb-2 flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-primary-400" />
                  Analytics and Reporting
                </h4>
                <p className="text-gray-400 text-sm">
                  Comprehensive reports showing beneficial ownership structures, investor segmentation, concentration analysis, 
                  flow attribution, and distribution insights.
                </p>
              </div>

              <div className="card-glass rounded-xl p-6">
                <h4 className="font-semibold mb-2 flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-accent-400" />
                  Platform Access
                </h4>
                <p className="text-gray-400 text-sm">
                  Web-based dashboard for uploading registers, viewing analysis results, managing disclosure requests, 
                  and accessing historical data.
                </p>
              </div>
            </div>

            <p className="text-sm text-gray-400 mt-4">
              Specific features and capabilities may vary depending on your subscription plan. We reserve the right to modify, 
              suspend, or discontinue any aspect of the Services with reasonable notice.
            </p>
          </section>

          {/* Account Registration */}
          <section>
            <h2 className="text-3xl font-bold mb-4">4. Account Registration and Eligibility</h2>
            
            <h3 className="text-2xl font-semibold mt-6 mb-3">4.1 Eligibility</h3>
            <p className="text-gray-300 mb-4">
              To use the Services, you must:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li>Be a legally recognised ETF issuer, asset manager, or authorised service provider</li>
              <li>Be at least 18 years of age</li>
              <li>Have the authority to bind your organisation to these Terms</li>
              <li>Not be prohibited from using the Services under applicable laws</li>
              <li>Not have had a previous account terminated for violation of our Terms</li>
            </ul>

            <h3 className="text-2xl font-semibold mt-6 mb-3">4.2 Account Information</h3>
            <p className="text-gray-300 mb-4">
              You agree to:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li>Provide accurate, current, and complete information during registration</li>
              <li>Maintain and promptly update your account information</li>
              <li>Keep your password secure and confidential</li>
              <li>Notify us immediately of any unauthorised access or security breach</li>
              <li>Accept responsibility for all activities under your account</li>
            </ul>

            <h3 className="text-2xl font-semibold mt-6 mb-3">4.3 Authorised Users</h3>
            <p className="text-gray-300">
              You are responsible for all Authorised Users' compliance with these Terms. You must ensure Authorised Users 
              maintain confidentiality and use the Services appropriately. You will be liable for any breaches by your 
              Authorised Users.
            </p>
          </section>

          {/* Subscription and Fees */}
          <section>
            <h2 className="text-3xl font-bold mb-4">5. Subscription Plans and Fees</h2>
            
            <h3 className="text-2xl font-semibold mt-6 mb-3">5.1 Subscription Plans</h3>
            <p className="text-gray-300 mb-4">
              We offer multiple subscription tiers (Starter, Professional, Enterprise) with varying features, usage limits, 
              and pricing. Details are available on our <Link to="/signup" className="text-primary-400 hover:text-primary-300">pricing page</Link>.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">5.2 Fees and Payment</h3>
            <div className="space-y-4">
              <p className="text-gray-300">
                <strong>Billing:</strong> Subscription fees are billed annually in advance unless otherwise agreed in writing. 
                Enterprise plans may have custom billing arrangements.
              </p>
              <p className="text-gray-300">
                <strong>Payment Terms:</strong> Payment is due within 30 days of invoice date. Late payments may incur interest 
                at 2% per month (or maximum rate permitted by law) and may result in suspension of Services.
              </p>
              <p className="text-gray-300">
                <strong>Price Changes:</strong> We may change our fees with 60 days' written notice. Price changes will not affect 
                your current Subscription Term but will apply upon renewal.
              </p>
              <p className="text-gray-300">
                <strong>Taxes:</strong> All fees are exclusive of taxes. You are responsible for all applicable taxes (VAT, sales tax, 
                withholding tax, etc.) except taxes based on our net income.
              </p>
            </div>

            <h3 className="text-2xl font-semibold mt-6 mb-3">5.3 Refunds</h3>
            <p className="text-gray-300 mb-4">
              Subscription fees are generally non-refundable except:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li>If we terminate your account without cause</li>
              <li>If we fail to deliver contracted Services</li>
              <li>As required by applicable law</li>
              <li>As specified in your Enterprise agreement</li>
            </ul>
            <p className="text-gray-300 mt-4">
              We may provide pro-rata refunds at our discretion for extraordinary circumstances.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">5.4 Free Trials and Demos</h3>
            <p className="text-gray-300">
              We may offer free trials or demo access. Trial accounts have limited features and data retention. 
              We may terminate trials at any time without notice. Converting a trial to a paid subscription 
              constitutes acceptance of these Terms.
            </p>
          </section>

          {/* Data and Intellectual Property */}
          <section>
            <h2 className="text-3xl font-bold mb-4">6. Data Ownership and Intellectual Property</h2>
            
            <h3 className="text-2xl font-semibold mt-6 mb-3">6.1 Your Data</h3>
            <div className="card-glass rounded-xl p-6 mb-4 border-l-4 border-primary-500">
              <p className="text-gray-300 mb-2">
                <strong>Ownership:</strong> You retain all rights to your Share Register Data. We claim no ownership of your data.
              </p>
              <p className="text-gray-300">
                <strong>License to Process:</strong> By uploading data, you grant us a limited, non-exclusive license to process, 
                analyse, and store your data solely for the purpose of providing the Services during your Subscription Term.
              </p>
            </div>

            <h3 className="text-2xl font-semibold mt-6 mb-3">6.2 Analysis Results</h3>
            <p className="text-gray-300 mb-4">
              Analysis Results are derived from your data using our proprietary methods. You own the specific Analysis Results 
              generated for you. We retain ownership of the underlying methodologies, algorithms, and anonymised aggregated insights.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">6.3 Our Intellectual Property</h3>
            <p className="text-gray-300 mb-4">
              The Services, including all software, databases, entity matching algorithms, user interfaces, trademarks, and content 
              (excluding your data), are owned by ETAnalytics and protected by copyright, trademark, and other intellectual property laws.
            </p>
            <p className="text-gray-300">
              You receive a limited, non-exclusive, non-transferable license to access and use the Services during your Subscription Term. 
              You may not:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4 mt-4">
              <li>Copy, modify, or create derivative works of our Services</li>
              <li>Reverse engineer, decompile, or disassemble our software</li>
              <li>Remove or alter any proprietary notices</li>
              <li>Use the Services to build a competing product</li>
              <li>Share your account access with third parties</li>
            </ul>

            <h3 className="text-2xl font-semibold mt-6 mb-3">6.4 Aggregated Data</h3>
            <p className="text-gray-300">
              We may use anonymised, aggregated data derived from multiple clients for product improvement, research, and industry 
              benchmarking. This aggregated data will not identify you or your specific investors.
            </p>
          </section>

          {/* Acceptable Use */}
          <section>
            <h2 className="text-3xl font-bold mb-4">7. Acceptable Use Policy</h2>
            <p className="text-gray-300 mb-4">
              You agree not to:
            </p>
            
            <div className="space-y-3">
              <div className="card-glass rounded-lg p-4 border-l-4 border-red-500">
                <strong className="text-red-400">Prohibited Activities</strong>
                <ul className="list-disc list-inside text-gray-400 space-y-1 ml-4 mt-2 text-sm">
                  <li>Upload inaccurate, fraudulent, or misleading data</li>
                  <li>Use the Services for illegal purposes or to violate any laws</li>
                  <li>Attempt to gain unauthorised access to our systems or other users' accounts</li>
                  <li>Introduce viruses, malware, or harmful code</li>
                  <li>Scrape, crawl, or use automated tools to extract data without permission</li>
                  <li>Overload our systems or interfere with others' use of the Services</li>
                  <li>Use disclosure mechanisms for harassment or bad faith purposes</li>
                  <li>Misrepresent your identity or affiliation</li>
                </ul>
              </div>

              <div className="card-glass rounded-lg p-4 border-l-4 border-accent-500">
                <strong className="text-accent-400">Data Upload Requirements</strong>
                <ul className="list-disc list-inside text-gray-400 space-y-1 ml-4 mt-2 text-sm">
                  <li>You must have legal right to share the Share Register Data you upload</li>
                  <li>Data must be accurate to the best of your knowledge</li>
                  <li>You must comply with all applicable data protection and securities laws</li>
                  <li>You are responsible for obtaining necessary consents for data processing</li>
                </ul>
              </div>
            </div>

            <p className="text-gray-300 mt-4">
              Violation of this Acceptable Use Policy may result in immediate suspension or termination of your account without refund.
            </p>
          </section>

          {/* Disclaimers and Limitations */}
          <section>
            <h2 className="text-3xl font-bold mb-4">8. Disclaimers and Limitations of Liability</h2>
            
            <div className="card-glass rounded-xl p-6 mb-6 bg-yellow-500/10 border-yellow-500/20">
              <div className="flex items-start gap-3">
                <AlertTriangle className="w-6 h-6 text-yellow-400 flex-shrink-0 mt-1" />
                <div>
                  <h4 className="font-semibold mb-2 text-yellow-400">Important Legal Disclaimers</h4>
                  <p className="text-gray-300 text-sm">
                    Please read this section carefully. It limits our liability and sets important terms regarding the Services.
                  </p>
                </div>
              </div>
            </div>

            <h3 className="text-2xl font-semibold mt-6 mb-3">8.1 Service Availability</h3>
            <p className="text-gray-300 mb-4">
              <strong>AS-IS BASIS:</strong> The Services are provided "as is" and "as available" without warranties of any kind, 
              whether express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, 
              or non-infringement.
            </p>
            <p className="text-gray-300">
              We do not guarantee the Services will be uninterrupted, error-free, or completely secure. We may experience downtime 
              for maintenance, upgrades, or unforeseen issues.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">8.2 Analysis Accuracy</h3>
            <p className="text-gray-300 mb-4">
              <strong>NO GUARANTEE OF ACCURACY:</strong> While we use commercially reasonable efforts to provide accurate entity 
              matching and analysis, we do not guarantee:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li>100% accuracy of entity identifications</li>
              <li>Complete beneficial ownership disclosure (dependent on third-party responses)</li>
              <li>Timeliness of disclosure responses from custodians</li>
              <li>Specific identification percentages or outcomes</li>
            </ul>
            <p className="text-gray-300 mt-4">
              Analysis Results should be verified and used as part of broader due diligence. They are not investment advice or 
              regulatory guidance.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">8.3 Limitation of Liability</h3>
            <div className="card-glass rounded-xl p-6 bg-red-500/10 border-red-500/20">
              <p className="text-gray-300 mb-4">
                <strong className="text-red-400">TO THE MAXIMUM EXTENT PERMITTED BY LAW:</strong>
              </p>
              <p className="text-gray-300 mb-4">
                ETAnalytics shall not be liable for any indirect, incidental, special, consequential, or punitive damages, 
                including but not limited to:
              </p>
              <ul className="list-disc list-inside text-gray-400 space-y-2 ml-4 text-sm">
                <li>Loss of profits, revenue, or business opportunities</li>
                <li>Loss of data or inability to access data</li>
                <li>Business interruption or reputational harm</li>
                <li>Cost of substitute services</li>
                <li>Regulatory fines or penalties</li>
                <li>Third-party claims</li>
              </ul>
              <p className="text-gray-300 mt-4">
                <strong>TOTAL LIABILITY CAP:</strong> Our total aggregate liability to you for all claims arising from or related 
                to the Services shall not exceed the amount you paid us in the 12 months preceding the claim, or £10,000, 
                whichever is greater.
              </p>
            </div>

            <h3 className="text-2xl font-semibold mt-6 mb-3">8.4 Exceptions</h3>
            <p className="text-gray-300">
              These limitations do not apply to: (a) our gross negligence or wilful misconduct; (b) death or personal injury 
              caused by our negligence; (c) fraud or fraudulent misrepresentation; or (d) any liability that cannot be excluded 
              by applicable law.
            </p>
          </section>

          {/* Indemnification */}
          <section>
            <h2 className="text-3xl font-bold mb-4">9. Indemnification</h2>
            <p className="text-gray-300 mb-4">
              You agree to indemnify, defend, and hold harmless ETAnalytics, its affiliates, officers, directors, employees, 
              and agents from any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) 
              arising from:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li>Your use or misuse of the Services</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of any third-party rights, including intellectual property or privacy rights</li>
              <li>Your Share Register Data or any claims that it infringes third-party rights</li>
              <li>Your breach of applicable laws or regulations</li>
              <li>Actions of your Authorised Users</li>
            </ul>
            <p className="text-gray-300 mt-4">
              We reserve the right to assume exclusive defence and control of any matter subject to indemnification, 
              at your expense.
            </p>
          </section>

          {/* Term and Termination */}
          <section>
            <h2 className="text-3xl font-bold mb-4">10. Term and Termination</h2>
            
            <h3 className="text-2xl font-semibold mt-6 mb-3">10.1 Term</h3>
            <p className="text-gray-300">
              These Terms commence when you first access the Services and continue until terminated by either party as provided below.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">10.2 Subscription Term</h3>
            <p className="text-gray-300 mb-4">
              Your Subscription Term begins on your subscription start date and continues for the period specified in your plan 
              (typically 12 months). Subscriptions automatically renew unless you cancel at least 30 days before the end of your 
              current term.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">10.3 Termination by You</h3>
            <p className="text-gray-300 mb-4">
              You may terminate your subscription by providing 30 days' written notice. Termination will be effective at the end 
              of your current Subscription Term. You remain liable for all fees incurred through the termination date.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">10.4 Termination by Us</h3>
            <p className="text-gray-300 mb-4">
              We may terminate or suspend your account:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li><strong>For Cause:</strong> Immediately if you breach these Terms, engage in prohibited activities, or fail to pay fees</li>
              <li><strong>For Convenience:</strong> With 60 days' written notice (pro-rata refund provided)</li>
              <li><strong>Legal Requirement:</strong> If required by law or court order</li>
            </ul>

            <h3 className="text-2xl font-semibold mt-6 mb-3">10.5 Effect of Termination</h3>
            <p className="text-gray-300 mb-4">
              Upon termination:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li>Your access to the Services will cease</li>
              <li>You must cease using all Analysis Results and materials</li>
              <li>We will retain your Share Register Data for 90 days, then delete it (unless legally required to retain)</li>
              <li>You may request a data export within 30 days of termination (fees may apply)</li>
              <li>All payment obligations for services rendered remain due</li>
              <li>Sections 6 (IP), 8 (Disclaimers), 9 (Indemnification), 11 (Confidentiality), and 14 (General) survive termination</li>
            </ul>
          </section>

          {/* Confidentiality */}
          <section>
            <h2 className="text-3xl font-bold mb-4">11. Confidentiality</h2>
            
            <h3 className="text-2xl font-semibold mt-6 mb-3">11.1 Mutual Obligations</h3>
            <p className="text-gray-300 mb-4">
              Both parties agree to protect each other's Confidential Information using at least the same degree of care used to 
              protect their own confidential information, but no less than reasonable care.
            </p>
            <p className="text-gray-300">
              <strong>"Confidential Information"</strong> includes: Share Register Data, Analysis Results, pricing terms, 
              technical specifications, business strategies, and any information marked as confidential or that reasonably 
              should be considered confidential.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">11.2 Exceptions</h3>
            <p className="text-gray-300 mb-4">
              Confidential Information does not include information that:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li>Is or becomes publicly available through no breach of this agreement</li>
              <li>Was rightfully known prior to disclosure</li>
              <li>Is independently developed without use of Confidential Information</li>
              <li>Is rightfully received from a third party without confidentiality restrictions</li>
            </ul>

            <h3 className="text-2xl font-semibold mt-6 mb-3">11.3 Permitted Disclosures</h3>
            <p className="text-gray-300">
              We may disclose Confidential Information: (a) to employees, contractors, and service providers who need to know 
              and are bound by confidentiality obligations; (b) as required by law or court order (with notice to you if permitted); 
              (c) as expressly permitted in these Terms.
            </p>
          </section>

          {/* Compliance and Legal */}
          <section>
            <h2 className="text-3xl font-bold mb-4">12. Compliance with Laws</h2>
            
            <h3 className="text-2xl font-semibold mt-6 mb-3">12.1 Your Compliance Obligations</h3>
            <p className="text-gray-300 mb-4">
              You are responsible for complying with all applicable laws in your use of the Services, including:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li><strong>Data Protection:</strong> GDPR, national data protection laws, obtaining necessary consents</li>
              <li><strong>Securities Laws:</strong> Insider trading rules, market abuse regulations, disclosure requirements</li>
              <li><strong>Company Law:</strong> Irish Companies Act, shareholder register management requirements</li>
              <li><strong>Export Controls:</strong> Sanctions, embargoes, and trade restrictions</li>
            </ul>

            <h3 className="text-2xl font-semibold mt-6 mb-3">12.2 Disclosure Framework</h3>
            <p className="text-gray-300">
              Our disclosure services operate under relevant legal frameworks (including Irish Companies Act provisions allowing 
              beneficial ownership enquiries). You represent that you have the legal right to make such enquiries for your ETF products.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">12.3 Anti-Money Laundering</h3>
            <p className="text-gray-300">
              You represent that your use of the Services complies with all applicable anti-money laundering, counter-terrorism 
              financing, and sanctions laws. We may request documentation to verify compliance.
            </p>
          </section>

          {/* Changes to Services and Terms */}
          <section>
            <h2 className="text-3xl font-bold mb-4">13. Changes to Services and Terms</h2>
            
            <h3 className="text-2xl font-semibold mt-6 mb-3">13.1 Service Changes</h3>
            <p className="text-gray-300">
              We may modify, update, or discontinue features of the Services at any time. We will provide reasonable notice 
              for material changes that negatively impact your use. We have no obligation to maintain deprecated features.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">13.2 Terms Updates</h3>
            <p className="text-gray-300 mb-4">
              We may update these Terms periodically. We will notify you of material changes by:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
              <li>Email to your registered address (at least 30 days before effective date)</li>
              <li>Prominent notice on our website</li>
              <li>In-app notification</li>
            </ul>
            <p className="text-gray-300 mt-4">
              Continued use of the Services after the effective date constitutes acceptance of updated Terms. If you do not 
              agree to changes, you must terminate your account before the effective date.
            </p>
          </section>

          {/* General Provisions */}
          <section>
            <h2 className="text-3xl font-bold mb-4">14. General Provisions</h2>
            
            <h3 className="text-2xl font-semibold mt-6 mb-3">14.1 Governing Law and Jurisdiction</h3>
            <p className="text-gray-300">
              These Terms are governed by the laws of England and Wales, without regard to conflict of law principles. 
              Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">14.2 Dispute Resolution</h3>
            <p className="text-gray-300">
              Before initiating litigation, parties agree to attempt to resolve disputes through good faith negotiation for 
              30 days. If unresolved, either party may pursue legal remedies. Nothing prevents either party from seeking 
              injunctive relief for intellectual property violations or confidentiality breaches.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">14.3 Force Majeure</h3>
            <p className="text-gray-300">
              Neither party shall be liable for delays or failures in performance resulting from causes beyond reasonable control, 
              including acts of God, natural disasters, terrorism, riots, telecommunications failures, cyberattacks, pandemics, 
              or government actions.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">14.4 Assignment</h3>
            <p className="text-gray-300">
              You may not assign or transfer these Terms or your account without our prior written consent. We may assign these 
              Terms to an affiliate or in connection with a merger, acquisition, or sale of assets with notice to you.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">14.5 Entire Agreement</h3>
            <p className="text-gray-300">
              These Terms, together with our Privacy Policy and any executed Enterprise agreements, constitute the entire agreement 
              between you and ETAnalytics regarding the Services and supersede all prior agreements, representations, and understandings.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">14.6 Severability</h3>
            <p className="text-gray-300">
              If any provision of these Terms is found unenforceable, that provision shall be modified to reflect the parties' 
              intention, and the remaining provisions shall remain in full effect.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">14.7 Waiver</h3>
            <p className="text-gray-300">
              Failure to enforce any provision does not constitute a waiver of that provision or our right to enforce it later.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">14.8 No Agency</h3>
            <p className="text-gray-300">
              These Terms do not create a partnership, joint venture, agency, or employment relationship between you and ETAnalytics.
            </p>

            <h3 className="text-2xl font-semibold mt-6 mb-3">14.9 Notices</h3>
            <p className="text-gray-300 mb-4">
              All notices must be in writing and delivered to:
            </p>
            <div className="card-glass rounded-xl p-6">
              <p className="text-gray-300 mb-2"><strong>To ETAnalytics:</strong></p>
              <p className="text-gray-400 text-sm">Email: <a href="mailto:accounts@etanalytics.co.uk" className="text-primary-400">accounts@etanalytics.co.uk</a></p>
              <p className="text-gray-400 text-sm">Subject: Legal Notice</p>
              
              <p className="text-gray-300 mt-4 mb-2"><strong>To You:</strong></p>
              <p className="text-gray-400 text-sm">The email address associated with your account</p>
            </div>
          </section>

          {/* Contact */}
          <section>
            <h2 className="text-3xl font-bold mb-4">15. Questions and Contact</h2>
            <div className="card-glass rounded-xl p-8 bg-primary-500/10 border-primary-500/20">
              <p className="text-gray-300 mb-4">
                If you have questions about these Terms of Service:
              </p>
              <div className="space-y-2 text-gray-300">
                <p><strong>Email:</strong> <a href="mailto:accounts@etanalytics.co.uk" className="text-primary-400 hover:text-primary-300">accounts@etanalytics.co.uk</a></p>
                <p><strong>Subject Line:</strong> Terms of Service Enquiry</p>
              </div>
              <p className="text-sm text-gray-400 mt-4">
                We will respond to terms enquiries within 5 business days.
              </p>
            </div>
          </section>

          {/* Legal Disclaimer */}
          <div className="card-glass rounded-xl p-6 mt-12 bg-yellow-500/10 border-yellow-500/20">
            <p className="text-sm text-gray-300">
              <strong>Legal Notice:</strong> These Terms of Service are provided as a template and should be reviewed and 
              customised by qualified legal counsel before publication. ETAnalytics recommends consulting with legal experts 
              specialising in technology services, financial services, and data protection to ensure compliance with all 
              applicable laws in your jurisdiction.
            </p>
          </div>

          {/* Acceptance */}
          <div className="card-glass rounded-xl p-8 mt-8 border-accent-500/30">
            <h3 className="text-xl font-semibold mb-4">Acceptance of Terms</h3>
            <p className="text-gray-300">
              By clicking "I Accept", creating an account, or using the Services, you acknowledge that you have read, understood, 
              and agree to be bound by these Terms of Service.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default TermsOfService

