"""Initial schema

Revision ID: 2ff7c98d3339
Revises: 
Create Date: 2026-01-18 15:24:47.324688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff7c98d3339'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=False),
    sa.Column('selected_plan', sa.String(length=50), nullable=False),
    sa.Column('num_etfs', sa.Integer(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index(op.f('ix_applications_access_token'), 'applications', ['access_token'], unique=True)
    op.create_index(op.f('ix_applications_company_name'), 'applications', ['company_name'], unique=False)
    op.create_index(op.f('ix_applications_contact_email'), 'applications', ['contact_email'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('requires_disclosure', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('lei', sa.String(length=20), nullable=True),
    sa.Column('parent_entity', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_pattern'), 'entities', ['pattern'], unique=True)
    op.create_table('etf_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('sedol', sa.String(length=7), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer_id', sa.String(length=50), nullable=False),
    sa.Column('asset_class', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('domicile', sa.String(length=100), nullable=True),
    sa.Column('current_aum', sa.Float(), nullable=True),
    sa.Column('yahoo_symbol', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etf_products'))
    )
    op.create_index(op.f('ix_etf_products_isin'), 'etf_products', ['isin'], unique=True)
    op.create_index(op.f('ix_etf_products_issuer_id'), 'etf_products', ['issuer_id'], unique=False)
    op.create_table('nav_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nav_history'))
    )
    op.create_index(op.f('ix_nav_history_date'), 'nav_history', ['date'], unique=False)
    op.create_index(op.f('ix_nav_history_isin'), 'nav_history', ['isin'], unique=False)
    op.create_table('registers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issuer_id', sa.String(length=50), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('as_of_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('total_holders', sa.Integer(), nullable=False),
    sa.Column('total_etfs', sa.Integer(), nullable=False),
    sa.Column('identified_percentage', sa.Float(), nullable=True),
    sa.Column('discovered_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registers'))
    )
    op.create_index(op.f('ix_registers_issuer_id'), 'registers', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_registers_status'), 'registers', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_documents_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_table('etf_columns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], name=op.f('fk_etf_columns_register_id_registers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etf_columns'))
    )
    op.create_index(op.f('ix_etf_columns_isin'), 'etf_columns', ['isin'], unique=False)
    op.create_table('register_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=500), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('resolved_entity', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('requires_disclosure', sa.Boolean(), nullable=False),
    sa.Column('disclosure_status', sa.String(length=50), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], name=op.f('fk_register_entries_register_id_registers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_register_entries'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_users_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('register_holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['register_entries.id'], name=op.f('fk_register_holdings_entry_id_register_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_register_holdings'))
    )
    op.create_index(op.f('ix_register_holdings_isin'), 'register_holdings', ['isin'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_refresh_token'), 'sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_register_holdings_isin'), table_name='register_holdings')
    op.drop_table('register_holdings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('register_entries')
    op.drop_index(op.f('ix_etf_columns_isin'), table_name='etf_columns')
    op.drop_table('etf_columns')
    op.drop_table('documents')
    op.drop_index(op.f('ix_registers_status'), table_name='registers')
    op.drop_index(op.f('ix_registers_issuer_id'), table_name='registers')
    op.drop_table('registers')
    op.drop_index(op.f('ix_nav_history_isin'), table_name='nav_history')
    op.drop_index(op.f('ix_nav_history_date'), table_name='nav_history')
    op.drop_table('nav_history')
    op.drop_index(op.f('ix_etf_products_issuer_id'), table_name='etf_products')
    op.drop_index(op.f('ix_etf_products_isin'), table_name='etf_products')
    op.drop_table('etf_products')
    op.drop_index(op.f('ix_entities_pattern'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_contact_email'), table_name='applications')
    op.drop_index(op.f('ix_applications_company_name'), table_name='applications')
    op.drop_index(op.f('ix_applications_access_token'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
