"""Ringfenced per-project file storage.

Every project gets its own directory under storage/projects/<id>/ with:
    photos/  uploaded photos (uuid filenames)
    videos/  AI-generated hero clips
    site/    the generated website (self-contained: index.html + copied assets)

All reads/writes go through this module, and any path derived from user input
is resolved and checked to stay inside the owning project's directory.
"""
import io
import logging
import shutil
import uuid
from pathlib import Path

from PIL import Image, ImageOps

from . import config

log = logging.getLogger("designo.storage")

# Web-delivery limits for photos copied into generated sites. Originals in
# photos/ stay untouched; only the site copies are optimised.
SITE_MAX_EDGE = 1920
SITE_JPEG_QUALITY = 82
SITE_OPTIMIZE_THRESHOLD = 350 * 1024  # leave small files alone


def project_dir(project_id: str) -> Path:
    # Project ids are uuid hex generated by us; still validate defensively.
    if not project_id.isalnum():
        raise ValueError("invalid project id")
    return config.PROJECTS_DIR / project_id


def ensure_project_dirs(project_id: str) -> Path:
    root = project_dir(project_id)
    for sub in ("photos", "videos", "site"):
        (root / sub).mkdir(parents=True, exist_ok=True)
    return root


def photos_dir(project_id: str) -> Path:
    return project_dir(project_id) / "photos"


def videos_dir(project_id: str) -> Path:
    return project_dir(project_id) / "videos"


def site_dir(project_id: str) -> Path:
    return project_dir(project_id) / "site"


def safe_resolve(base: Path, relative: str) -> Path:
    """Resolve `relative` under `base`, refusing anything that escapes it."""
    target = (base / relative).resolve()
    base = base.resolve()
    if not (target == base or target.is_relative_to(base)):
        raise PermissionError("path escapes project storage")
    return target


def save_photo_bytes(project_id: str, data: bytes, original_name: str) -> str:
    """Persist an uploaded photo; returns the stored filename."""
    ext = Path(original_name).suffix.lower()
    if ext not in config.ALLOWED_PHOTO_EXTENSIONS:
        raise ValueError(f"unsupported file type: {ext or 'none'}")
    filename = f"{uuid.uuid4().hex}{ext}"
    dest = photos_dir(project_id) / filename
    dest.write_bytes(data)
    return filename


def delete_photo_file(project_id: str, filename: str) -> None:
    path = safe_resolve(photos_dir(project_id), filename)
    path.unlink(missing_ok=True)


def write_site(project_id: str, html: str) -> None:
    """Write the generated site and copy its assets in, so site/ is self-contained."""
    root = ensure_project_dirs(project_id)
    site = root / "site"
    (site / "index.html").write_text(html, encoding="utf-8")

    site_photos = site / "photos"
    if site_photos.exists():
        shutil.rmtree(site_photos)
    site_photos.mkdir(parents=True)
    for src in (root / "photos").iterdir():
        if src.is_file():
            _copy_optimized(src, site_photos / src.name)

    site_videos = site / "videos"
    if site_videos.exists():
        shutil.rmtree(site_videos)
    shutil.copytree(root / "videos", site_videos)


def _copy_optimized(src: Path, dest: Path) -> None:
    """Copy a photo into the site, downscaling/recompressing large ones for web delivery."""
    if src.stat().st_size <= SITE_OPTIMIZE_THRESHOLD:
        shutil.copy2(src, dest)
        return
    try:
        img = Image.open(src)
        img = ImageOps.exif_transpose(img)
        img.thumbnail((SITE_MAX_EDGE, SITE_MAX_EDGE), Image.LANCZOS)
        buf = io.BytesIO()
        if src.suffix.lower() == ".png" and (img.mode in ("RGBA", "P") and "A" in img.getbands()):
            img.save(buf, "PNG", optimize=True)
        else:
            if img.mode != "RGB":
                img = img.convert("RGB")
            img.save(buf, "JPEG", quality=SITE_JPEG_QUALITY, optimize=True, progressive=True)
        data = buf.getvalue()
        if len(data) < src.stat().st_size:
            dest.write_bytes(data)
            log.info("optimized %s: %dKB -> %dKB", src.name,
                     src.stat().st_size // 1024, len(data) // 1024)
            return
    except Exception:
        log.exception("photo optimization failed for %s, copying original", src.name)
    shutil.copy2(src, dest)


def read_site_html(project_id: str) -> str | None:
    path = site_dir(project_id) / "index.html"
    if not path.exists():
        return None
    return path.read_text(encoding="utf-8")


def delete_project_storage(project_id: str) -> None:
    root = project_dir(project_id)
    if root.exists():
        shutil.rmtree(root)


def export_site_zip(project_id: str) -> Path:
    """Zip the generated site for download; returns the zip path."""
    site = site_dir(project_id)
    if not (site / "index.html").exists():
        raise FileNotFoundError("no generated site")
    zip_base = project_dir(project_id) / "export"
    zip_path = Path(shutil.make_archive(str(zip_base), "zip", root_dir=site))
    return zip_path
